### ISSUE TITLE
Paytm logo is not showing

### ISSUE THREAD

**Issue by spantheslayer** [wontone18/paytm-payment-gateway-bagisto-laravel#2]
Everything is working except in the payment page in customer facing site (frontend) the paytm logo is not coming/showing.

<img width="1250" alt="image" src="https://github.com/wontone18/paytm-payment-gateway-bagisto-laravel/assets/61844611/2f5c35e4-6ec8-4796-9e9f-350e2df392dd">

**Comment by wontone18** [comment]
in the updated version you can able to upload the logo from the admin section.

**Comment by wontone18** [comment]
this issue is fixed please download the latest version.
